### ISSUE TITLE
A question (silly...)

### ISSUE THREAD

**Issue by Tanzin01** [luka177/mmc-to-usb#1]
How to know  if I fulfill this?
* kernel must have CONFIG_USB_CONFIGFS_MASS_STORAGE enabled)

[Tried searching, unable find anything...]

**Comment by luka177** [comment]
You need to enable it in defconfig

**Comment by luka177** [comment]
And for sure compile kernel after that
Example of config: https://github.com/HelloVolla/android_kernel_volla_mt6763/blob/halium-9.0/arch/arm64/configs/k63v2_64_bsp_defconfig#L409

**Comment by Tanzin01** [comment]
Thanks a lot :)
